# Generated by Django 5.1 on 2024-09-19 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_borrowbook_due_date_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 18, 14, 15, 51, 132011, tzinfo=datetime.timezone.utc)),
        ),
    ]
