# Generated by Django 5.1 on 2024-09-19 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookcategory_slug_alter_borrowbook_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 18, 15, 37, 37, 19533, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(related_name='category', to='books.bookcategory'),
        ),
    ]
