# Generated by Django 5.1 on 2024-09-19 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_books_category_alter_borrowbook_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 18, 15, 42, 22, 787810, tzinfo=datetime.timezone.utc)),
        ),
    ]
