# Generated by Django 5.1 on 2024-09-19 17:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_borrowbook_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 18, 17, 30, 59, 150696, tzinfo=datetime.timezone.utc)),
        ),
    ]
