# Generated by Django 5.1 on 2024-09-19 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_borrowbook_borrower_alter_borrowbook_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='returned',
        ),
        migrations.AddField(
            model_name='books',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 18, 17, 37, 9, 198928, tzinfo=datetime.timezone.utc)),
        ),
    ]
