# Generated by Django 5.1 on 2024-09-20 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_books_returned_alter_borrowbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 19, 2, 52, 44, 646779, tzinfo=datetime.timezone.utc)),
        ),
    ]
