# Generated by Django 5.1 on 2024-09-20 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_borrowbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 19, 3, 19, 57, 23706, tzinfo=datetime.timezone.utc)),
        ),
    ]
