# Generated by Django 5.1 on 2024-09-20 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_borrowbook_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 19, 3, 40, 37, 613910, tzinfo=datetime.timezone.utc)),
        ),
    ]
