# Generated by Django 5.1 on 2024-12-07 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_borrowbook_returned_alter_borrowbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 5, 6, 52, 32, 695378, tzinfo=datetime.timezone.utc)),
        ),
    ]
