# Generated by Django 5.1 on 2024-12-13 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_borrowbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 11, 16, 42, 48, 675659, tzinfo=datetime.timezone.utc)),
        ),
    ]
