# Generated by Django 5.1 on 2024-09-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
